### ISSUE TITLE
Too many errors on installation

### ISSUE THREAD

**Issue by onigetoc** [llm-tools/embedJs#21]
Too many errors on installation

At first i tryed with npm without success than tryed with yarn.

```
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\L*****\embedJs-main> yarn install
yarn install v1.22.19
warning ..\..\..\package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning @qdrant/js-client-rest@1.8.2: The engine "pnpm" appears to be invalid.
warning @qdrant/openapi-typescript-fetch@1.2.6: The engine "pnpm" appears to be invalid.
error @typescript-eslint/eslint-plugin@7.7.0: The engine "node" is incompatible with this module. Expected version "^18.18.0 || >=20.0.0". Got "18.14.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by adhityan** [comment]
The issue is what it says in the error message -

Expected node version "^18.18.0 || >=20.0.0". Got "18.14.0"

The library supports and requires node version 18.18.0 minimum. Older versions of node than this might work but were not tested and not therefore not supported. All newer versions after this should work. 

It does not matter what package manager you use as long as you are using an older not-supported version of node.

**Comment by adhityan** [comment]
Could you try installing the package with a supported version of node and let me know if you still see an error?

**Comment by adhityan** [comment]
@onigetoc where you able to check this with an updated node version?
